"""
Derive a deterministic version string for each trained model from its file mtime.

We use mtime instead of a hash or git rev because the model artifacts are
regenerated by `python -m ml.training.train_models` — that script's outputs
change with every run, and the mtime is the cheapest stable signal.

Format: ISO-8601 UTC second-precision, e.g. "2026-05-17T16:08:42Z".
"""
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path

from backend.core.logging import get_logger

logger = get_logger(__name__)

_TRAINED_DIR = Path(__file__).resolve().parents[2] / "ml" / "models" / "trained"

_MODEL_FILES = {
    "regression_random_forest": "regression_random_forest.joblib",
    "regression_gradient_boost": "regression_gradient_boost.joblib",
    "lstm": "lstm_energy_forecast.keras",
    "anomaly_detector": "anomaly_detector.joblib",
}


def _mtime_version(path: Path) -> str:
    ts = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    # second precision is plenty — keeps the string short and stable.
    return ts.replace(microsecond=0).isoformat().replace("+00:00", "Z")


# We cache by key so we don't stat the file on every prediction. The cache is
# cleared when the process restarts; retraining therefore requires an app
# restart to pick up a new version. Acceptable for this app — drift logging
# tolerates slight version lag.
@lru_cache(maxsize=8)
def get_model_version(key: str) -> str | None:
    filename = _MODEL_FILES.get(key)
    if not filename:
        return None
    path = _TRAINED_DIR / filename
    if not path.exists():
        logger.warning(f"Model file missing for version lookup: {path}")
        return None
    return _mtime_version(path)
