import { Activity } from "lucide-react"

import { Alert, AlertDescription } from "@/components/ui/alert"

import { LiveStream } from "./live-stream"

export default function RealtimePage() {
  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-3xl font-bold tracking-tight">Real-time</h1>
        <p className="text-sm text-muted-foreground">
          Live energy readings streamed from the backend over WebSocket.
        </p>
      </header>

      <Alert>
        <Activity className="size-4" />
        <AlertDescription>
          Demo mode — data is generated by the backend simulator every 5 seconds. Stream real sensor readings into
          Supabase to see live production data.
        </AlertDescription>
      </Alert>

      <LiveStream />
    </div>
  )
}
